In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score


digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2, random_state=42)



In [2]:
lr = LogisticRegression(solver='lbfgs', max_iter=1000)
lr.fit(X_train, y_train)
lr_score = lr.score(X_test, y_test)
lr_score

0.9583333333333334

In [3]:
svm = SVC(gamma = 'auto')
svm.fit(X_train, y_train)
svm_score = svm.score(X_test, y_test)

In [4]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf_score = rf.score(X_test, y_test)

In [5]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [6]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print("TRAIN:", train_index, "TEST:", test_index)
    

TRAIN: [3 4 5 6 7 8] TEST: [0 1 2]
TRAIN: [0 1 2 6 7 8] TEST: [3 4 5]
TRAIN: [0 1 2 3 4 5] TEST: [6 7 8]


In [7]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [8]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]
    
    scores_logistic.append(get_score(LogisticRegression(solver='lbfgs', max_iter=1000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma = 'auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [9]:
scores_logistic

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]

In [10]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [11]:
scores_rf

[0.9298831385642737, 0.9565943238731218, 0.9298831385642737]

In [12]:
cross_val_score(LogisticRegression(solver='lbfgs', max_iter=1000), digits.data, digits.target, cv=3)

array([0.91986644, 0.94156928, 0.91652755])

In [13]:
cross_val_score(SVC(gamma = 'auto'), digits.data, digits.target, cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [14]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=3)

array([0.93656093, 0.94490818, 0.92487479])

In [15]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=3)

array([0.94323873, 0.95492487, 0.91986644])

In [16]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target, cv=10)
np.average(scores1)

np.float64(0.8648013656114216)

In [17]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target, cv=10)
np.average(scores2)

np.float64(0.9398975791433891)

In [18]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target, cv=10)
np.average(scores3)

np.float64(0.9348789571694599)

In [19]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=10)
np.average(scores4)

np.float64(0.9493606455617629)